networks:
  default:
    name: "proxy"
    external: true
  nextcloud-backend:
    internal: true
    ipam:
      config:
        - subnet: "10.255.255.8/29"

volumes:
  redis:
  mariadb:
  app:

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - /home/docker/env/nextcloud/mariadb.env
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - nextcloud-backend
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - nextcloud-backend
    volumes:
      - redis:/data

  app:
    image: nextcloud
    restart: always
    env_file:
      - /home/docker/env/nextcloud/app.env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - default
      - nextcloud-backend
    links:
      - db:db
      - redis:redis
    volumes:
      - app:/var/www/html
      - /home/docker/data/nextcloud/data:/var/www/html/data
      - /home/docker/data/nextcloud/geoip:/usr/share/GeoIP:ro

  geoip:
    image: tkrs/maxmind-geoipupdate
    restart: always
    volumes:
      - /home/docker/data/nextcloud/geoip:/usr/share/GeoIP
    env_file:
      - /home/docker/env/nextcloud/geoip.env

  cron:
    image: nextcloud
    restart: always
    volumes:
      - app:/var/www/html
      - /home/docker/config/nextcloud/app/cronfile:/var/spool/cron/crontabs/www-data
    entrypoint: "/cron.sh"
    depends_on:
      - db
      - redis
