networks:
  default:
    name: "proxy"
    external: true
  npm-backend:
    internal: true
    ipam:
      config:
        - subnet: "10.255.255.0/29"


volumes:
  mariadb:

services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-app
    restart: always
    env_file:
      - /home/docker/env/proxy/npm.env
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /home/docker/config/proxy/npm:/data
      - /home/docker/data/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 10.200.0.1
      npm-backend:
    depends_on:
      - db
    links:
      - db:db

  db:
    image: jc21/mariadb-aria
    container_name: proxy-db
    restart: always
    env_file:
      - /home/docker/env/proxy/mariadb.env
    volumes:
      - mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - npm-backend
