watch:
  workers: 20
  schedule: "0 */6 * * *"
  jitter: 30s
  firstCheckNotif: false
  runOnStartup: true

notif:
  mail:
    host: "mx.public.domain"
    port: 25
    ssl: false
    localName: resolvable.hostname
    from: diun@public.domain
    to:
      - liam@public.domain

providers:
  docker:
    watchByDefault: true
